image:
  repository: ghcr.io/kube-vip/kube-vip
  pullPolicy: Always
  tag: v0.8.9

config:
  address: "10.2.2.110"

env:
  vip_interface: ""
  vip_arp: "true"
  lb_enable: "true"
  lb_port: "6443"
  vip_cidr: "32"
  cp_enable: "true"
  svc_enable: "true"
  svc_election: "true"
  vip_leaderelection: "true"
  vip_leaseduration: "5"

serviceAccount:
  create: true
  annotations: {}
  name: "kube-vip"

affinity: {}
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: Exists
    - matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists

securityContext:
  capabilities:
    add:
      - NET_ADMIN
      - NET_RAW

nodeSelector: 
  node-role.kubernetes.io/control-plane: "true"

tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
